### ISSUE TITLE
Introduce yourself...

### ISSUE THREAD

**Issue by susanBuck** [susanBuck/e15-spring22#1]
Hi everyone - 

Welcome to the Spring 2022 semester! Let's get to know each other...

I'm a web programmer and educator. When not teaching, I like to spend as much time outside as possible - hiking, gardening, and tending to a little hobby farm where I live, about 1 hour outside of Boston.

In the past, I've taught at Wellesley, UPenn, and UMiami. When working in industry I was the lead developer for an online e-commerce store. You can read more about my background/experience here: [susanbuck.net](https://susanbuck.net)

All in all, I love creating things with code and teaching others how to do the same.

**Reply to this post introducing yourself - where are you from, what do you do for work and fun, and what brought you to this course?**

**Comment by YvaGithub** [comment]
Hello all,
My name is Yvaral Louis-Jame. I am originally from Haiti. I have been living in Boston for almost two decades. While here, I attended Wentworth Institute of Technology where I received a Bachelor degree in Electronic Engineering. I have been a course taker at the Extension School for a few years now. This Spring I will be applying for the Master of Liberal Arts (ALM) in Extension Studies, field: Information Management Systems. Although I am not admitted yet, I believe I am only three courses away from accomplishing all the course requirements. I work for the Boston Water and Sewer Commission as Senior Computer Operator/Helpdesk. When I am not working, I can be pretty handy around the house. I can be either replacing a power supply from a 55" tv mounted on the wall, I can be fixing a burst copper water pipe, I can be replacing a gas stove, a gas laundry dryer or a water heater. I can also be replacing a power steering pump or an alternator at my 2007 Honda Accord etc. What do I do for fun? I prank my children sometimes and I like watching Forensics Files on TV. I also like going to the gym where I meet some friends to talk more than working out. I also started to pick up where I left off in learning to play guitar. I recently bought myself a guitar and some books. We will see how it goes.

**Comment by gkorodi** [comment]
Hello everybody!

My name is Gábor Koródi, and I am originally from Hungary, but I have been living in and around Boston for the past 20+ years.

I am a software programmer and work on various projects with Java, PHP, and Python. I am trying to be a full-stack developer, which means I write, test, and release code, and manage the cloud infrastructure (mostly AWS) it is running on.

Outside of work, I like to race in open-water competitions (in the summer-fall) and dream about the beach during the winter. I also race in triathlons, which I find funny, since I am not an "[age grouper](https://townandcamp.com/running/what-are-triathlon-age-groups/)" but rather a "[weight grouper](https://healthfully.com/460031-what-is-a-clydesdale-division-in-triathlons.html)".

I am interested in learning the latest and greatest technologies and getting formal instructions on frameworks, such as Laravel in PHP and/or Vue in JS. Also interested in getting familiar with the rich ecosystem that is built around Laravel.

**Comment by dauger27** [comment]
Hello. I'm Dan Auger and I live in Chicago but previously lived in Boston for almost 10 years. I'm a network engineer who spends most of my time off from work either playing board games or reading some fiction books. I have an interest in learning more about frameworks like Laravel.

**Comment by pllealfunes** [comment]
Hi everyone,

My name is Paula and I am from Massachusetts. I am half way through the Digital Media Design MLA degree at HES. I have taken Susan's Vue.js and introductory PHP courses, and I am excited to learn more from her.

In my free time I enjoy reading, photography, learning more about web development as well as working on my own projects, being around loved ones, and I am currently learning how to crochet.

I hope we all have a great semester!

**Comment by mgarimelHES** [comment]
Hi Friends,

My name is Murty and I am from Colorado. I am working on my ALM in information systems. I have taken Susan's E2 class last fall and it's a a great PHP course, and I am excited to learn more from her this Spring 22.

Looking forward to a great semester!

**Comment by luannebe** [comment]
Hi All, 

My name is Luann. I too am from Colorado, but am now a free-lance web developer living outside of Boston, Massachusetts. Most of my work is front-end, but I want to learn more about server-side technologies. In particular, I hope to develop a web app for a non-profit client in Washington DC.

Over the years, I've taken many courses at the extension school. I'm very impressed by Susan's teaching and look forward to learning a lot this semester!

I enjoy reading and yoga, as well as X-country skiing...which is a good thing since there is a blizzard raging outside and skiing may soon be the best mode of travel.

**Comment by patrickgarsow-harvard** [comment]
> X-country skiing...which is a good thing since there is a blizzard raging outside and skiing may soon be the best mode of travel.

You are correct, welcome to living in the Northeast. I live in Upstate NY next to the Canadian board same here. I love the seasons and always find it funny how much the weather impacts us every year though we should be acclimated.

**Comment by patrickgarsow-harvard** [comment]
Hello everyone!

My name is Patrick Garsow. I am from a small town in Upstate NY called Plattsburgh. I have worked in the IT industry for 19 years, first working in healthcare, then for EMC out of Hopkinton, MA, then for Dell Technologies, and now am a Storage Services Architect at Harvard Medical School.

My previous education, interest, and outside freelance work is with web development. I have been programming using LAMP stacks and PHP for for over 15 years. My interest in this class is to become acclimated with Laravel and Vue.js as I haven't worked with either of these in the past. Most recently I have been using CakePHP which is a framework that I noted was not called out by the instructor's examples. In reviewing week one's reading material I noted it is common to ask if I am using the right technology to get the job done. I have asked that many times and feel like I am always left questioning myself.

 I have also worked with React.js, Angular.js, and Node.js. I have built custom web applications for many different industries/areas including politics, NGO's and non-profits, education, retail, and hospitality.

I am excited about the class, excited to help out any way I can, and look forward to working with everyone!

**Comment by archerdave** [comment]
Hi!  I'm David Harvill.  I live in Marlborough, Massachusetts, which isn't too far from Boston.  Although I was born on the west coast, I've lived in New England since I was seven.  My paying job is tech support for Harvard Business School, where I interact with just about everybody, from all over the globe.   For fun, I like to read, take photos, program, play with hardware, and am lately also investigating woodworking.  Sleep fits in...  somewhere.

**Comment by gabichuela85** [comment]
Hi everyone! My name is Gaby and I live just north of Boston in Revere. I took Web Programming for Beginners with PHP last semester, and am looking forward to diving into Laravel. I am currently working on completing the web technologies certificate at the extension school. 

I currently work at Harvard as a financial associate. For fun I love to read, snowboard and hike. Looking forward to a great semester!

**Comment by xul889** [comment]
Hello everyone,

My name is Xunqi Liu. You can just go by my English nick name 'Frank' Liu. I graduated from Miami University(Ohio) in 2020 with a Bachelor's degree, majoring in Economics and minoring in Computer Science. So I don't have really strong coding background. Now I live in Seattle, Washington. In my daily life, I like to play table tennis and I also like hiking and climbing, and I am a big fan of playing DJI drone.

**Comment by susanBuck** [comment]
Thanks everyone for the intros! Was nice to "meet" everyone. : )
