### ISSUE TITLE
View Controller Related Question

### ISSUE THREAD

**Issue by xul889** [susanBuck/e15-spring22#17]
Why we'd better not put php code into view, because sometimes it is easier if we put php code into view files.

**Comment by susanBuck** [comment]
Some PHP code in a view file is okay if it's for display purposes. Any PHP logic, though, should not happen in the view. 

It all comes back to separation of concerns. The view's job/role is to display results, so that's where we go to find display specific code. Similarly, we expect logic-specific code to be in the controller (at least for now in our simple view-controller only pattern; later we'll expand on this). 

Following these clear patterns makes our code more predictable for ourselves and other developers who may be working on the code.

It may seem nitpicky in the scope/scale of the small project we've built so far, but it's all about building good habits and learning best practices for expanding into bigger projects.

**Comment by xul889** [comment]
It makes a lot of sense. I should cultivate this programming habit from the first day I have coded. It is informative. Thank you so much for the explanations.
