### ISSUE TITLE
Project2 - Not able to create it using 'composer'

### ISSUE THREAD

**Issue by mgarimelHES** [susanBuck/e15-spring22#25]
Hello Friends!

 I am not sure if anyone has seen this issue, I am getting the following error while running the *composer* command as shown below -

![image](https://user-images.githubusercontent.com/64241541/155854364-5a3a233e-ff9d-44fc-8f55-c6adb5306690.png)

Any pointers are greatly appreciated.

Thanks

**Comment by mgarimelHES** [comment]
It is resolved after installing the php8.0-curl by running this command on my dev server -

sudo apt-get install php8.0-curl

Thanks

**Comment by susanBuck** [comment]
Thanks for sharing your solution, @mgarimelHES.

I just did a fresh new install and received similar errors about missing extensions. Not sure why we didn't face this in Week 4 when we did our first installations. Does look like Laravel has bumped up from 9.1 to 9.2 since then, so that could be why.

Here are the extensions I found I needed to install:

```bash
> sudo apt-get install php8.1-dom php8.1-curl
```

I'll create an announcement post about this to make sure everyone is aware of it. Thanks for bringing it to my attention!

**Comment by susanBuck** [comment]
Did some digging, and can confirm both **dom** and **curl** are recent additions to the extension requirement list.

Ref: 
https://github.com/laravel/docs/commit/e24a8df206eb75d05df2deb5695025e8b6838d0c
https://github.com/laravel/docs/commit/22b8f24ea0c4d9305906ad8acd6476bf806b5db2

**Comment by mgarimelHES** [comment]
Thanks for the update, it helped me .

Regards,

Murthy Garimella

HES - ALM
