### ISSUE TITLE
CSS Formatting for Project 1

### ISSUE THREAD

**Issue by dauger27** [susanBuck/e15-spring22#5]
How much time/effort would you want us to put into the look and feel of the website for Project 1? Should we build out our own custom CSS for this or could we utilize the example site that you provided as a template?

**Comment by susanBuck** [comment]
You're not graded on style, so it's really up to you. You can keep it real minimal - especially P1 since it's such a basic interface. You can use the CSS from my example if you'd like.

Projects 2 and 3 are a bit more open-ended in what you'll be creating and sometimes students like to style the site to match what they're creating. This level of presentation/effort is always noted/appreciated, but not something you would lose points for if you didn't have.

I will say this - I would always put styling/design last. Make sure core functionality is working and requirements are met before falling down any CSS rabbit holes. : )
